"use client";
import { useState } from "react";
import { Icon } from "@/ui/icons";
import type { MarketRouteNarrative } from "@/application/conversation/contracts";

const prompts=["Why is this worth pursuing?","What are you still unsure about?","Why is this the right contact?","What should I do next?"];
export function AskMarketRoute({campaignId,companyId,opportunityId,canDirect=false,returnTo}:{campaignId:string;companyId:string;opportunityId?:string|null;canDirect?:boolean;returnTo?:string}){
  const [question,setQuestion]=useState("");const [answer,setAnswer]=useState<MarketRouteNarrative|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState<string|null>(null);
  const ask=async(value?:string)=>{const q=(value??question).trim();if(q.length<3||loading)return;setLoading(true);setError(null);try{const r=await fetch("/api/conversation/opportunity",{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({campaignId,companyId,question:q})});const body=await r.json() as {narrative?:MarketRouteNarrative;error?:string};if(!r.ok||!body.narrative)throw new Error(body.error??"ASK_FAILED");setAnswer(body.narrative);setQuestion(q);}catch{setError("I couldn't answer that from the current MarketRoute state. The opportunity data itself is unchanged.");}finally{setLoading(false);}};
  return <section className="mr-ask-marketroute"><header><div className="mr-ask-marketroute__orb"><Icon name="spark" size={18}/></div><div><span>ASK MARKETROUTE</span><h2>Ask about this opportunity.</h2><p>Ask anything about the company, the reason to pursue it or a current route in. I’ll only use what MarketRoute has actually established.</p></div></header>
    <div className="mr-ask-marketroute__prompts">{prompts.map(p=><button key={p} type="button" onClick={()=>ask(p)} disabled={loading}>{p}</button>)}</div>{canDirect&&opportunityId&&<div className="mr-ask-marketroute__commands"><span>ASK MARKETROUTE TO DO MORE</span><form action={`/api/opportunities/${opportunityId}/review`} method="post"><input type="hidden" name="campaignId" value={campaignId}/><input type="hidden" name="companyId" value={companyId}/><input type="hidden" name="returnTo" value={returnTo??`/app/opportunities/${campaignId}/${companyId}`}/><input type="hidden" name="note" value="Customer command: deepen the current company research before the next decision."/><button name="decision" value="RETURN_TO_RESEARCH" type="submit"><Icon name="research" size={13}/>Research this further</button></form><form action={`/api/opportunities/${opportunityId}/review`} method="post"><input type="hidden" name="campaignId" value={campaignId}/><input type="hidden" name="companyId" value={companyId}/><input type="hidden" name="returnTo" value={returnTo??`/app/opportunities/${campaignId}/${companyId}`}/><input type="hidden" name="note" value="Customer command: investigate another viable route into this organisation."/><button name="decision" value="RETURN_TO_RESEARCH" type="submit"><Icon name="route" size={13}/>Find another route</button></form></div>}
    <div className="mr-ask-marketroute__input"><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();void ask();}}} placeholder="Ask why this company matters, what is uncertain, or which route to use…" maxLength={320}/><button type="button" onClick={()=>ask()} disabled={loading||question.trim().length<3}>{loading?"Thinking…":"Ask"}<Icon name="arrow" size={14}/></button></div>
    {error&&<div className="mr-ask-marketroute__error"><Icon name="warning" size={14}/>{error}</div>}
    {answer&&<article className="mr-ask-marketroute__answer"><span>MARKETROUTE</span><h3>{answer.headline}</h3><p>{answer.summary}</p>{answer.uncertainties.length>0&&<div><small>Still checking</small><p>{answer.uncertainties[0]}</p></div>}<footer><strong>Next move</strong><span>{answer.nextAction}</span></footer></article>}
  </section>;
}
