import { asObject, asObjectArray, formatDateTime, shortFingerprint, text } from "@/application/read-model/presentation";
import type { ClaimProvenanceReadModel } from "@/application/read-model/contracts";
import { StatusBadge } from "@/ui/primitives/status-badge";
import { humanStatus } from "@/ui/application/language";
import { Icon } from "@/ui/icons";

export function ProvenanceDrawer({model,closeHref}:{model:ClaimProvenanceReadModel;closeHref:string}){
  const snapshot=asObject(model.truthSnapshot),claim=asObject(model.claim),evidence=asObjectArray(model.evidence);
  const truthState=text(snapshot.truthState,"UNKNOWN");
  return <aside className="mr-provenance-drawer" aria-label="Claim provenance"><div className="mr-provenance-drawer__backdrop"/><div className="mr-provenance-drawer__panel"><header><div><div className="mr-kicker"><span/> EVIDENCE DETAIL</div><h2>{humanStatus(text(claim.claimKey,"Claim"))}</h2><p>{humanStatus(text(claim.predicate,"Canonical claim"))} · {text(claim.canonicalValue,"structured value")}</p></div><a href={closeHref} className="mr-icon-button" aria-label="Close provenance">×</a></header><div className="mr-provenance-drawer__truth"><StatusBadge label={humanStatus(truthState)} title={truthState} tone={truthState==="CONTRADICTED"?"red":"blue"}/><dl><div><dt>Evidence sufficiency</dt><dd>{Math.round(Number(snapshot.evidenceSufficiency??0))}%</dd></div><div><dt>Freshness</dt><dd>{Math.round(Number(snapshot.freshnessCoverage??0))}%</dd></div><div><dt>Snapshot</dt><dd>{shortFingerprint(snapshot.snapshotFingerprint)}</dd></div><div><dt>Revalidate</dt><dd>{formatDateTime(snapshot.nextRevalidationAt)}</dd></div></dl></div><div className="mr-provenance-drawer__evidence"><div className="mr-panel-label">Evidence ({model.returnedEvidenceCount}{model.truncated?` of ${model.evidenceCount}`:""})</div>{evidence.length===0?<p className="mr-muted-copy">No evidence rows returned.</p>:evidence.map((item)=>{const source=asObject(item.source);const polarity=text(item.polarity);return <article key={text(item.evidenceId)}><div className="mr-provenance-drawer__evidence-head"><StatusBadge compact label={humanStatus(polarity)} title={polarity} tone={polarity==="CONTRADICTS"?"red":"green"}/><span>{formatDateTime(item.observedAt)}</span></div><p>{text(item.excerpt,text(item.structuredValue,"Structured evidence"))}</p><footer><Icon name="database" size={13}/><span>{text(source.publisherDomain,text(source.sourceKind,"Source"))}</span>{typeof source.canonicalUrl==="string"&&source.canonicalUrl&&<a href={source.canonicalUrl} target="_blank" rel="noreferrer">Open source ↗</a>}</footer></article>})}</div></div></aside>
}
