import { PostgrestRpcClient,databaseConfigFromEnvironment } from "./postgrest-rpc";
export interface ActivationJob{job_id:string;organisation_id:string;seller_business_id:string;seller_name:string;canonical_domain:string|null;website_url:string;created_by_user_id:string;objective_text:string;target_market_text:string;hard_constraints_text:string|null;no_hard_constraints:boolean;attempt_count:number}
export class ProductionActivationRepository{
  constructor(private readonly rpc=new PostgrestRpcClient(databaseConfigFromEnvironment())){}
  async claim(workerId:string,at:string):Promise<ActivationJob|null>{const v=await this.rpc.call<ActivationJob[]|ActivationJob|null>("marketroute_claim_workspace_activation_v1",{p_worker_id:workerId,p_at:at});if(Array.isArray(v))return v[0]??null;return v??null;}
  complete(jobId:string,workerId:string,result:Record<string,unknown>,at:string){return this.rpc.call<void>("marketroute_complete_workspace_activation_v1",{p_job_id:jobId,p_worker_id:workerId,p_result_json:result,p_at:at});}
  fail(jobId:string,workerId:string,errorCode:string,retryable:boolean,at:string){return this.rpc.call<void>("marketroute_fail_workspace_activation_v1",{p_job_id:jobId,p_worker_id:workerId,p_error_code:errorCode,p_retryable:retryable,p_at:at});}
  createCampaign(organisationId:string,sellerBusinessId:string,objectiveText:string){return this.rpc.call<string>("marketroute_create_activation_campaign_v1",{p_organisation_id:organisationId,p_seller_business_id:sellerBusinessId,p_objective_text:objectiveText});}
  ensureCompany(organisationId:string,campaignId:string,c:{name:string;domain:string;websiteUrl:string;countryCode:string|null}){return this.rpc.call<string>("marketroute_ensure_activation_company_v1",{p_organisation_id:organisationId,p_campaign_id:campaignId,p_name:c.name,p_domain:c.domain,p_website_url:c.websiteUrl,p_country_code:c.countryCode});}
  setResearchPolicy(input:{organisationId:string;campaignId:string;dailyBudgetUsd:number;maxJobCostUsd:number;maxConcurrentJobs:number;maxWorkUnitsPerPlan:number;refreshHorizonHours:number}){return this.rpc.call("marketroute_set_research_policy_v1",{p_organisation_id:input.organisationId,p_campaign_id:input.campaignId,p_daily_budget_usd:input.dailyBudgetUsd,p_max_job_cost_usd:input.maxJobCostUsd,p_max_concurrent_jobs:input.maxConcurrentJobs,p_max_work_units_per_plan:input.maxWorkUnitsPerPlan,p_refresh_horizon_hours:input.refreshHorizonHours});}
}
export function productionActivationRepositoryFromEnvironment(){return new ProductionActivationRepository();}
