import { PostgrestRpcClient,databaseConfigFromEnvironment } from "./postgrest-rpc";
export interface ActivationJob{job_id:string;organisation_id:string;seller_business_id:string;seller_name:string;canonical_domain:string|null;website_url:string;created_by_user_id:string|null;campaign_name:string|null;seller_offering_text:string;objective_text:string;target_market_text:string;hard_constraints_text:string|null;no_hard_constraints:boolean;attempt_count:number}
export interface ActivationBankCandidate{company_id:string;name:string;canonical_domain:string;website_url:string;country_code:string|null;industry_key:string;core_complete:boolean;profile_complete:boolean;routes_complete:boolean;contacts_complete:boolean}
export interface AnonymousActivationPolicy{runId:string;lifetimeBudgetUsd:number;researchExpiresAt:string;targetCount:number}
export interface AnonymousDiscoveryExtensionJob{
  job_id:string;run_id:string;organisation_id:string;campaign_id:string;seller_business_id:string;seller_name:string;canonical_domain:string|null;website_url:string;
  objective_text:string;target_market_text:string;target_count:number;scoped_count:number;remaining_count:number;attempt_count:number;existing_domains:string[];
}
export interface AnonymousDiscoveryExtensionLink{company_id:string;scoped_count:number;target_count:number;inserted_scope:boolean}
export interface AnonymousDiscoveryExtensionCompletion{status:string;scoped_count:number;target_count:number}
export class ProductionActivationRepository{
  constructor(private readonly rpc=new PostgrestRpcClient(databaseConfigFromEnvironment())){}
  async claim(workerId:string,at:string):Promise<ActivationJob|null>{const v=await this.rpc.call<ActivationJob[]|ActivationJob|null>("marketroute_claim_workspace_activation_v3",{p_worker_id:workerId,p_at:at});if(Array.isArray(v))return v[0]??null;return v??null;}
  stage(jobId:string,workerId:string,stage:string,progress:number,detail:Record<string,unknown>={}){return this.rpc.call<void>("marketroute_set_workspace_activation_stage_v1",{p_job_id:jobId,p_worker_id:workerId,p_stage:stage,p_progress:progress,p_detail_json:detail,p_at:new Date().toISOString()});}
  complete(jobId:string,workerId:string,result:Record<string,unknown>,at:string){return this.rpc.call<void>("marketroute_complete_workspace_activation_v1",{p_job_id:jobId,p_worker_id:workerId,p_result_json:result,p_at:at});}
  fail(jobId:string,workerId:string,errorCode:string,retryable:boolean,at:string){return this.rpc.call<void>("marketroute_fail_workspace_activation_v1",{p_job_id:jobId,p_worker_id:workerId,p_error_code:errorCode,p_retryable:retryable,p_at:at});}
  createCampaign(jobId:string,organisationId:string,sellerBusinessId:string,campaignName:string|null,objectiveText:string){return this.rpc.call<string>("marketroute_create_activation_campaign_v3",{p_job_id:jobId,p_organisation_id:organisationId,p_seller_business_id:sellerBusinessId,p_campaign_name:campaignName,p_objective_text:objectiveText});}
  ensureCompany(organisationId:string,campaignId:string,c:{name:string;domain:string;websiteUrl:string;countryCode:string|null}){return this.rpc.call<string>("marketroute_ensure_activation_company_v1",{p_organisation_id:organisationId,p_campaign_id:campaignId,p_name:c.name,p_domain:c.domain,p_website_url:c.websiteUrl,p_country_code:c.countryCode});}
  setResearchPolicy(input:{organisationId:string;campaignId:string;dailyBudgetUsd:number;maxJobCostUsd:number;maxConcurrentJobs:number;maxWorkUnitsPerPlan:number;refreshHorizonHours:number}){return this.rpc.call("marketroute_set_research_policy_v1",{p_organisation_id:input.organisationId,p_campaign_id:input.campaignId,p_daily_budget_usd:input.dailyBudgetUsd,p_max_job_cost_usd:input.maxJobCostUsd,p_max_concurrent_jobs:input.maxConcurrentJobs,p_max_work_units_per_plan:input.maxWorkUnitsPerPlan,p_refresh_horizon_hours:input.refreshHorizonHours});}
  anonymousPolicy(organisationId:string):Promise<AnonymousActivationPolicy|null>{return this.rpc.call("marketroute_anonymous_discovery_policy_v1",{p_organisation_id:organisationId});}
  async bankCandidates(industryKeys:string[],countryCodes:string[],limit:number):Promise<ActivationBankCandidate[]>{const v=await this.rpc.call<ActivationBankCandidate[]|ActivationBankCandidate|null>("marketroute_activation_bank_candidates_v1",{p_industry_keys:industryKeys,p_country_codes:countryCodes,p_limit:limit});if(Array.isArray(v))return v;return v?[v]:[];}
  async claimAnonymousExtension(workerId:string,at:string):Promise<AnonymousDiscoveryExtensionJob|null>{const v=await this.rpc.call<AnonymousDiscoveryExtensionJob[]|AnonymousDiscoveryExtensionJob|null>("marketroute_claim_anonymous_discovery_extension_v1",{p_worker_id:workerId,p_at:at});if(Array.isArray(v))return v[0]??null;return v??null;}
  async linkAnonymousExtensionCompany(jobId:string,workerId:string,c:{name:string;domain:string;websiteUrl:string;countryCode:string|null},at:string):Promise<AnonymousDiscoveryExtensionLink|null>{const v=await this.rpc.call<AnonymousDiscoveryExtensionLink[]|AnonymousDiscoveryExtensionLink|null>("marketroute_link_anonymous_discovery_extension_company_v1",{p_job_id:jobId,p_worker_id:workerId,p_name:c.name,p_domain:c.domain,p_website_url:c.websiteUrl,p_country_code:c.countryCode,p_at:at});if(Array.isArray(v))return v[0]??null;return v??null;}
  async completeAnonymousExtension(jobId:string,workerId:string,result:Record<string,unknown>,at:string):Promise<AnonymousDiscoveryExtensionCompletion|null>{const v=await this.rpc.call<AnonymousDiscoveryExtensionCompletion[]|AnonymousDiscoveryExtensionCompletion|null>("marketroute_complete_anonymous_discovery_extension_v1",{p_job_id:jobId,p_worker_id:workerId,p_result_json:result,p_at:at});if(Array.isArray(v))return v[0]??null;return v??null;}
  failAnonymousExtension(jobId:string,workerId:string,errorCode:string,retryable:boolean,at:string){return this.rpc.call<void>("marketroute_fail_anonymous_discovery_extension_v1",{p_job_id:jobId,p_worker_id:workerId,p_error_code:errorCode,p_retryable:retryable,p_at:at});}
}
export function productionActivationRepositoryFromEnvironment(){return new ProductionActivationRepository();}
