import { workspaceSessionOrRedirect } from "@/app/app/_lib/session";
import { applicationReadServiceFromEnvironment } from "@/application/read-model/service";
import { asObject,asObjectArray,companyProfile,money,numberValue,statusTone,text } from "@/application/read-model/presentation";
import { EmptyState,humanStatus,IntelligenceTable,MetricCard,PageHeader,Panel,SectionHeading,StatusBadge } from "@/ui";

export default async function CampaignPage({params}:{params:Promise<{campaignId:string}>}){
  const {campaignId}=await params;
  const {workspace}=await workspaceSessionOrRedirect();
  const model=await applicationReadServiceFromEnvironment().campaign({organisationId:workspace.organisationId,campaignId});
  const campaign=asObject(model.campaign),metrics=asObject(model.metrics),research=asObject(model.research),budget=asObject(research.budget),profiles=asObjectArray(model.opportunities).map(companyProfile);
  const state=text(campaign.workflowState,"UNKNOWN");
  return <div>
    <PageHeader eyebrow="CAMPAIGN OVERVIEW" title={text(campaign.name,"Campaign")} description={text(campaign.objectiveText,"Commercial objective not yet declared.")} actions={<div className="mr-header-badge-row"><StatusBadge label={humanStatus(state)} title={state} tone={statusTone(state)}/><StatusBadge label={model.engagementPolicy==="AUTOPILOT"?"Autopilot engagement":"Human approval"} tone="slate"/></div>}/>
    <section className="mr-metric-grid"><MetricCard label="Companies in scope" value={String(numberValue(metrics.scopedCompanies))} meta="Currently being evaluated"/><MetricCard label="Qualified opportunities" value={String(numberValue(metrics.materialisedOpportunities))} meta="Commercially materialised"/><MetricCard label="Research used today" value={money(budget.spentTodayUsd)} meta="AI and acquisition spend"/><MetricCard label="Research budget remaining" value={money(budget.remainingTodayUsd)} meta="Available today" accent/></section>
    <Panel><SectionHeading eyebrow="Commercial pipeline" title="Companies that have earned opportunity state" description="A company appears here only after MarketRoute can represent the commercial case and its current authority chain. Technical R4/R5/R6 states remain available in the row for auditability."/>{profiles.length===0?<EmptyState icon="opportunities" title="No qualified opportunities yet" body="MarketRoute is still researching this campaign, or no company has yet earned the required commercial, route and contact authority."/>:<IntelligenceTable head={["Company","Commercial status","Your workflow","Commercial case","Route","Contact","Access"]}>{profiles.map(p=><tr key={p.companyId}><td><a href={`/app/opportunities/${campaignId}/${p.companyId}`}><strong>{p.companyName}</strong><small>{p.canonicalDomain??"No domain"}</small></a></td><td><StatusBadge compact label={humanStatus(p.disposition)} title={p.disposition} tone={statusTone(p.disposition)}/></td><td>{humanStatus(p.workflowState,"Not reviewed")}</td><td><span className="mr-table-state" title={p.commercialReality}>{humanStatus(p.commercialReality)}</span></td><td><span className="mr-table-state" title={p.routeAuthority}>{humanStatus(p.routeAuthority)}</span></td><td><span className="mr-table-state" title={p.contactAuthority}>{humanStatus(p.contactAuthority)}</span></td><td>{p.authorisedRoutes} qualified / {p.structuralRoutes} structural</td></tr>)}</IntelligenceTable>}</Panel>
  </div>
}
