import { ApplicationReadRepository, applicationReadRepositoryFromEnvironment } from "../../platform/database/application-read-repository";
import { commercialAccessServiceFromEnvironment, type CommercialAccess } from "../commercial/service";
import type { CampaignReadModel, ClaimProvenanceReadModel, CommandCentreReadModel, CompanyIntelligenceReadModel, EngagementReadModel, CompanyIndexReadModel, ResearchActivityReadModel, EngagementIndexReadModel, ProvenanceClaimIndexReadModel, RouteDisplayReadModel,JsonObject } from "./contracts";
import { assertCanonicalApplicationRead, assertCanonicalEngagementRead } from "./validation";

function currentIso(value?:string):string {const date=value?new Date(value):new Date();if(!Number.isFinite(date.getTime()))throw new Error("MARKETROUTE_APPLICATION_READ_TIME_INVALID");return date.toISOString();}
function requiredId(value:string,name:string):string {const v=value?.trim();if(!v)throw new Error(`MARKETROUTE_APPLICATION_READ_ID_REQUIRED:${name}`);return v;}
function text(value:unknown){return typeof value==="string"?value:"";}
function object(value:unknown):JsonObject{return value&&typeof value==="object"&&!Array.isArray(value)?value as JsonObject:{};}
function countBy(values:JsonObject[],key:string){const out:Record<string,number>={};for(const value of values){const k=text(value[key])||"UNKNOWN";out[k]=(out[k]??0)+1;}return out as unknown as JsonObject;}

export class ApplicationReadService {
  private readonly commercial=commercialAccessServiceFromEnvironment();
  private readonly accessCache=new Map<string,Promise<CommercialAccess>>();
  constructor(private readonly repository:ApplicationReadRepository){}
  private access(organisationId:string){let value=this.accessCache.get(organisationId);if(!value){value=this.commercial.access(organisationId);this.accessCache.set(organisationId,value);}return value;}
  async commercialAccess(command:{organisationId:string}):Promise<CommercialAccess>{return this.access(requiredId(command.organisationId,"organisationId"));}
  private async assertCompanyVisible(organisationId:string,companyId:string){const access=await this.access(organisationId);if(!this.commercial.canReadCompany(access,companyId))throw new Error("MARKETROUTE_DISCOVERY_UPGRADE_REQUIRED");return access;}
  private async assertOpportunityVisible(organisationId:string,opportunityId:string){const access=await this.access(organisationId);if(!this.commercial.canReadOpportunity(access,opportunityId))throw new Error("MARKETROUTE_DISCOVERY_UPGRADE_REQUIRED");return access;}
  private filterCampaign(model:CampaignReadModel,access:CommercialAccess):CampaignReadModel{
    if(access.mode==="FULL"||access.mode==="PAID")return model;const allowed=new Set(access.mode==="DISCOVERY_FREE"?access.companyIds:[]);const opportunities=model.opportunities.filter(value=>allowed.has(text(value.companyId)));const metrics=object(model.metrics);return{...model,metrics:{...metrics,materialisedOpportunities:opportunities.length,dispositionCounts:countBy(opportunities,"disposition"),workflowCounts:countBy(opportunities,"workflowState"),lifecycleCounts:countBy(opportunities,"lifecycleState")},opportunities};
  }
  async commandCentre(command:{organisationId:string;at?:string}):Promise<CommandCentreReadModel>{
    const organisationId=requiredId(command.organisationId,"organisationId"),at=currentIso(command.at);const value=await this.repository.commandCentre(organisationId,at);let model=assertCanonicalApplicationRead<CommandCentreReadModel>(value,"COMMAND_CENTRE");const access=await this.access(organisationId);if(access.mode==="FULL"||access.mode==="PAID")return model;
    // Command Centre is deliberately a lightweight summary read. Do not fetch the
    // full campaign read per row merely to redact Discovery counters; that path
    // evaluates every company authority profile and turns navigation into N+1 work.
    if(access.mode!=="DISCOVERY_FREE")return {...model,campaigns:model.campaigns.map(item=>({...item,metrics:{...object(item.metrics),materialisedOpportunities:0,dispositionCounts:{},workflowCounts:{},lifecycleCounts:{}}}))};
    const visible=Math.max(0,access.opportunityIds.length);
    let remaining=visible;
    model={...model,campaigns:model.campaigns.map(item=>{
      const metrics=object(item.metrics),materialised=Math.max(0,Number(metrics.materialisedOpportunities??0)||0),allowed=Math.min(materialised,remaining);remaining=Math.max(0,remaining-allowed);
      const dispositions=object(metrics.dispositionCounts),workflows=object(metrics.workflowCounts),lifecycle=object(metrics.lifecycleCounts);
      const ready=Math.min(allowed,Math.max(0,Number(dispositions.ACTIONABLE??0)||0));
      const reviewable=Math.min(allowed,Math.max(0,Number(workflows.REVIEWABLE??0)||0));
      const approved=Math.min(Math.max(0,allowed-reviewable),Math.max(0,Number(workflows.APPROVED??0)||0));
      const engaged=Math.min(Math.max(0,allowed-reviewable-approved),Math.max(0,Number(workflows.ENGAGED??0)||0));
      return {...item,metrics:{...metrics,materialisedOpportunities:allowed,dispositionCounts:{...dispositions,ACTIONABLE:ready},workflowCounts:{REVIEWABLE:reviewable,APPROVED:approved,ENGAGED:engaged},lifecycleCounts:{...lifecycle,AUTHORITY_READY:ready}}};
    })};return model;
  }
  async campaign(command:{organisationId:string;campaignId:string;at?:string}):Promise<CampaignReadModel>{const organisationId=requiredId(command.organisationId,"organisationId");const value=await this.repository.campaign(organisationId,requiredId(command.campaignId,"campaignId"),currentIso(command.at));const model=assertCanonicalApplicationRead<CampaignReadModel>(value,"CAMPAIGN");return this.filterCampaign(model,await this.access(organisationId));}
  async company(command:{organisationId:string;campaignId:string;companyId:string;at?:string}):Promise<CompanyIntelligenceReadModel>{const organisationId=requiredId(command.organisationId,"organisationId"),companyId=requiredId(command.companyId,"companyId");await this.assertCompanyVisible(organisationId,companyId);const value=await this.repository.company(organisationId,requiredId(command.campaignId,"campaignId"),companyId,currentIso(command.at));return assertCanonicalApplicationRead<CompanyIntelligenceReadModel>(value,"COMPANY_INTELLIGENCE");}
  async companyIndex(command:{organisationId:string;campaignId:string;limit?:number;offset?:number;at?:string}):Promise<CompanyIndexReadModel>{const organisationId=requiredId(command.organisationId,"organisationId"),campaignId=requiredId(command.campaignId,"campaignId"),limit=Math.max(1,Math.min(command.limit??100,250)),offset=Math.max(0,command.offset??0);const value=await this.repository.companyIndex(organisationId,campaignId,limit,offset,currentIso(command.at));let model=assertCanonicalApplicationRead<CompanyIndexReadModel>(value,"COMPANY_INDEX");const access=await this.access(organisationId);if(access.mode!=="FULL"&&access.mode!=="PAID"){const allowed=new Set(access.mode==="DISCOVERY_FREE"?access.companyIds:[]);const companies=model.companies.filter(company=>allowed.has(text(company.companyId)));model={...model,totalCount:companies.length,offset:0,returnedCount:companies.length,companies};}return model;}
  async researchActivity(command:{organisationId:string;campaignId:string;at?:string}):Promise<ResearchActivityReadModel>{const value=await this.repository.researchActivity(requiredId(command.organisationId,"organisationId"),requiredId(command.campaignId,"campaignId"),currentIso(command.at));return assertCanonicalApplicationRead<ResearchActivityReadModel>(value,"RESEARCH_ACTIVITY");}
  async engagementIndex(command:{organisationId:string;campaignId:string;limit?:number;offset?:number;at?:string}):Promise<EngagementIndexReadModel>{const organisationId=requiredId(command.organisationId,"organisationId"),limit=Math.max(1,Math.min(command.limit??100,250)),offset=Math.max(0,command.offset??0);const value=await this.repository.engagementIndex(organisationId,requiredId(command.campaignId,"campaignId"),limit,offset,currentIso(command.at));let model=assertCanonicalApplicationRead<EngagementIndexReadModel>(value,"ENGAGEMENT_INDEX");const access=await this.access(organisationId);if(access.mode!=="FULL"&&access.mode!=="PAID"){const allowed=new Set(access.mode==="DISCOVERY_FREE"?access.opportunityIds:[]);const items=model.items.filter(item=>allowed.has(text(item.opportunityId)));model={...model,totalCount:items.length,offset:0,returnedCount:items.length,items};}return model;}
  async routeDisplay(command:{organisationId:string;campaignId:string;companyId:string;at?:string}):Promise<RouteDisplayReadModel>{const organisationId=requiredId(command.organisationId,"organisationId"),companyId=requiredId(command.companyId,"companyId");await this.assertCompanyVisible(organisationId,companyId);const value=await this.repository.routeDisplay(organisationId,requiredId(command.campaignId,"campaignId"),companyId,currentIso(command.at));return assertCanonicalApplicationRead<RouteDisplayReadModel>(value,"ROUTE_DISPLAY");}
  async provenanceClaimIndex(command:{organisationId:string;campaignId:string;companyId:string;at?:string}):Promise<ProvenanceClaimIndexReadModel>{const organisationId=requiredId(command.organisationId,"organisationId"),companyId=requiredId(command.companyId,"companyId");await this.assertCompanyVisible(organisationId,companyId);const value=await this.repository.provenanceClaimIndex(organisationId,requiredId(command.campaignId,"campaignId"),companyId,currentIso(command.at));return assertCanonicalApplicationRead<ProvenanceClaimIndexReadModel>(value,"PROVENANCE_CLAIM_INDEX");}
  async engagement(command:{opportunityId:string;organisationId?:string;at?:string}):Promise<EngagementReadModel>{const opportunityId=requiredId(command.opportunityId,"opportunityId");if(command.organisationId)await this.assertOpportunityVisible(requiredId(command.organisationId,"organisationId"),opportunityId);const value=await this.repository.engagement(opportunityId,currentIso(command.at));return assertCanonicalEngagementRead<EngagementReadModel>(value);}
  async claimProvenance(command:{organisationId:string;campaignId:string;companyId:string;claimSnapshotId:string;at?:string}):Promise<ClaimProvenanceReadModel>{const organisationId=requiredId(command.organisationId,"organisationId"),companyId=requiredId(command.companyId,"companyId");await this.assertCompanyVisible(organisationId,companyId);const value=await this.repository.claimProvenance(organisationId,requiredId(command.campaignId,"campaignId"),companyId,requiredId(command.claimSnapshotId,"claimSnapshotId"),currentIso(command.at));return assertCanonicalApplicationRead<ClaimProvenanceReadModel>(value,"CLAIM_PROVENANCE");}
}
export function applicationReadServiceFromEnvironment(){return new ApplicationReadService(applicationReadRepositoryFromEnvironment());}
