import { PublicPageShell } from "@/ui";
export default function Privacy(){return <PublicPageShell eyebrow="PRIVACY" title="Privacy, explained plainly." intro="MarketRoute handles account data, business research inputs and public-source commercial intelligence. This notice explains what we process, why we process it and the choices available to you.">
  <article><span>01</span><div><h2>Who operates MarketRoute</h2><p>MarketRoute is a product of Truth Index Systems. For privacy questions, access requests, corrections or deletion requests, contact <a href="mailto:jaspal.sanghera@truthindexsystems.co.uk">jaspal.sanghera@truthindexsystems.co.uk</a>.</p></div></article>
  <article><span>02</span><div><h2>Information you give us</h2><p>This can include your account email, workspace and business details, website, commercial objective, target-market brief, support messages and the instructions you give MarketRoute while using the service.</p></div></article>
  <article><span>03</span><div><h2>Anonymous discovery</h2><p>The free discovery experience uses a signed browser identifier and a coarse network abuse-control hash so we can enforce the one-run limit and protect research spend. MarketRoute does not store the raw IP address in the anonymous discovery record.</p></div></article>
  <article><span>04</span><div><h2>Commercial research data</h2><p>MarketRoute researches organisations and business contacts using public and permitted sources. That can include company information, professional roles, business contact channels, source URLs, evidence records and freshness or verification state. The product is designed to keep source evidence and uncertainty visible rather than presenting unsupported contact data as fact.</p></div></article>
  <article><span>05</span><div><h2>Why we process information</h2><p>We process information to provide and secure the service, carry out requested commercial research, maintain evidence and audit lineage, manage subscriptions, prevent abuse, support customers and improve product reliability. Where personal data is involved, the appropriate lawful basis depends on the purpose and may include contract, legal obligation, legitimate interests or consent where required.</p></div></article>
  <article><span>06</span><div><h2>Service providers</h2><p>MarketRoute uses specialist infrastructure and processing providers to operate the service, including cloud/database infrastructure, AI processing and Stripe for subscription billing. MarketRoute does not need to receive or store your full payment-card details when Stripe processes checkout.</p></div></article>
  <article><span>07</span><div><h2>Retention and deletion</h2><p>We keep information for as long as it is needed to provide the service, preserve security and billing records, maintain evidence lineage, meet legal obligations or resolve disputes. Retention varies by record type. You can ask us to close an account or request deletion; some records may need to be retained where there is a legal, security or audit reason.</p></div></article>
  <article><span>08</span><div><h2>Your rights</h2><p>Depending on the circumstances, data-protection law may give you rights to access, correct, erase, restrict or object to processing, and to receive certain data in portable form. You may also complain to the UK Information Commissioner’s Office if you have concerns about how personal information is handled.</p></div></article>
  <article><span>09</span><div><h2>Changes</h2><p>We will update this notice when the way MarketRoute processes information materially changes. Last updated: 18 August 2026.</p></div></article>
</PublicPageShell>}
