import type { ReactNode } from "react";
import { MarketRouteLogo } from "@/ui/brand/marketroute-logo";
import { Icon } from "@/ui/icons";
import { NavigationList } from "@/ui/shell/navigation-list";
import { WorkspaceTopbar } from "@/ui/shell/workspace-topbar";

export interface ShellWorkspace { organisationId:string; name:string; role:string; }
interface AppShellProps { children:ReactNode; workspace:ShellWorkspace; workspaces:ShellWorkspace[]; userEmail:string|null; }
export function AppShell({children,workspace,workspaces,userEmail}:AppShellProps){return <div className="mr-app-shell"><div className="mr-app-grid" aria-hidden="true"/><aside className="mr-sidebar"><a href="/" className="mr-sidebar__brand" aria-label="MarketRoute home"><MarketRouteLogo/></a><div className="mr-sidebar__workspace"><span>Workspace</span><strong>{workspace.name}</strong><small>{workspace.role}</small>{workspaces.length>1&&<form action="/api/session/workspace" method="post"><select name="organisationId" defaultValue={workspace.organisationId} aria-label="Switch workspace">{workspaces.map((item)=><option key={item.organisationId} value={item.organisationId}>{item.name}</option>)}</select><button type="submit">Switch</button></form>}</div><NavigationList/><div className="mr-sidebar__footer"><div className="mr-system-state"><span className="mr-system-state__pulse" aria-hidden="true"/><div><strong>Genesis online</strong><small>Canonical application read model</small></div></div><a href="/design-system" className="mr-sidebar__utility">Design system <Icon name="chevron" size={14}/></a></div></aside><div className="mr-app-main"><WorkspaceTopbar userEmail={userEmail}/><details className="mr-mobile-nav"><summary aria-label="Open navigation"><Icon name="menu" size={18}/> Navigation</summary><NavigationList mobile/></details><main className="mr-app-content">{children}</main></div></div>}
