import { PublicPageShell } from "@/ui";
export default function Terms(){return <PublicPageShell eyebrow="TERMS" title="Clear terms for a commercial product." intro="These terms govern use of MarketRoute. The service is designed for business and professional use and provides commercial research and decision-support tooling, not guaranteed sales outcomes.">
  <article><span>01</span><div><h2>The service</h2><p>MarketRoute researches markets, organisations and potential routes to business contacts, then presents evidence-backed commercial intelligence. Outputs can change as sources change, evidence expires or new research becomes available.</p></div></article>
  <article><span>02</span><div><h2>Accounts and workspaces</h2><p>You are responsible for keeping account credentials secure and for activity carried out through your workspace. Do not attempt to bypass plan limits, access another customer’s workspace or interfere with MarketRoute’s security, research controls or entitlement system.</p></div></article>
  <article><span>03</span><div><h2>Free discovery</h2><p>MarketRoute may provide one bounded anonymous discovery run and a limited number of free opportunities. Free access is subject to abuse controls, research limits and availability. Creating an account can be required to save or use contact routes.</p></div></article>
  <article><span>04</span><div><h2>Paid plans</h2><p>Paid subscriptions renew on the cadence shown at checkout until cancelled. Prices and included research capacity are shown before purchase. Subscription management and cancellation are available through the secure billing portal. Access changes only after MarketRoute receives verified billing state from its payment provider.</p></div></article>
  <article><span>05</span><div><h2>Using commercial intelligence responsibly</h2><p>You are responsible for how you use contact information, outreach drafts and research outputs, including compliance with applicable privacy, marketing, employment, sector and communications rules. MarketRoute does not authorise unlawful outreach or guarantee that a communication is lawful for your specific recipient or circumstances.</p></div></article>
  <article><span>06</span><div><h2>Accuracy and availability</h2><p>MarketRoute is designed to expose evidence, freshness and uncertainty, but public-source information can be incomplete, delayed or wrong. You should use appropriate judgement before relying on an output for a material commercial decision. We may change, suspend or maintain parts of the service to preserve security and reliability.</p></div></article>
  <article><span>07</span><div><h2>Intellectual property</h2><p>MarketRoute, Genesis, the product design, software and system-generated presentation remain the intellectual property of Truth Index Systems or its licensors. You retain rights in information you submit, subject to the permissions needed for MarketRoute to process it and provide the service.</p></div></article>
  <article><span>08</span><div><h2>Liability</h2><p>MarketRoute is a commercial decision-support tool. It does not promise a particular lead volume, response rate, contract, revenue outcome or uninterrupted availability. Nothing in these terms excludes liability that cannot lawfully be excluded.</p></div></article>
  <article><span>09</span><div><h2>Contact and changes</h2><p>Questions about these terms can be sent to <a href="mailto:jaspal.sanghera@truthindexsystems.co.uk">jaspal.sanghera@truthindexsystems.co.uk</a>. Material changes will be reflected on this page. Last updated: 18 August 2026.</p></div></article>
</PublicPageShell>}
