import { createHash } from "node:crypto";
import { OpenAIResponsesClient,openAIModel } from "../../platform/ai/openai-responses";
import { conversationCacheRepositoryFromEnvironment,type ConversationCacheRepository } from "../../platform/database/conversation-cache-repository";
import type { AnonymousDiscoveryStatusRecord } from "../../platform/database/anonymous-discovery-repository";
import type { AnonymousPipelineStage } from "../discovery/service";
import type { CampaignReadModel,CommandCentreReadModel,CompanyIntelligenceReadModel,RouteDisplayReadModel } from "../read-model/contracts";
import { MARKETROUTE_CONVERSATION_CONTRACT_VERSION,type MarketRouteNarrative,type MarketRouteNarrativeScope,type NarrativeFactSet } from "./contracts";

const outputSchema={type:"object",additionalProperties:false,properties:{headline:{type:"string",minLength:3,maxLength:120},summary:{type:"string",minLength:8,maxLength:650},whyItMatters:{type:"string",minLength:3,maxLength:500},known:{type:"array",maxItems:6,items:{type:"string",minLength:2,maxLength:260}},uncertainties:{type:"array",maxItems:5,items:{type:"string",minLength:2,maxLength:260}},recommendation:{type:"string",minLength:2,maxLength:350},nextAction:{type:"string",minLength:2,maxLength:300},evidenceReferences:{type:"array",maxItems:12,items:{type:"string",minLength:1,maxLength:200}}},required:["headline","summary","whyItMatters","known","uncertainties","recommendation","nextAction","evidenceReferences"]} as const;
const internalLanguage=/\bR[456]\b|UDOSIB|epistemic|fingerprint|reasoning kind|authority record|canonical read model/i;
function stable(value:unknown):string{if(Array.isArray(value))return`[${value.map(stable).join(",")}]`;if(value&&typeof value==="object"){const row=value as Record<string,unknown>;return`{${Object.keys(row).sort().map(k=>`${JSON.stringify(k)}:${stable(row[k])}`).join(",")}}`;}return JSON.stringify(value);}
function fingerprint(value:unknown){return createHash("sha256").update(stable(value)).digest("hex");}
function text(value:unknown,fallback=""){return typeof value==="string"&&value.trim()?value.trim():fallback;}
function object(value:unknown):Record<string,unknown>{return value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};}
function objectArray(value:unknown){return Array.isArray(value)?value.map(object):[];}
function number(value:unknown){const n=Number(value);return Number.isFinite(n)?n:0;}
function boolean(value:unknown){return value===true;}
function human(value:string){return value.replace(/_/g," ").toLowerCase().replace(/(^|\s)\S/g,c=>c.toUpperCase());}
function cleanList(values:unknown,max:number){return(Array.isArray(values)?values:[]).filter((v):v is string=>typeof v==="string").map(v=>v.trim()).filter(Boolean).slice(0,max);}
function ttlHours(scope:MarketRouteNarrativeScope){return scope==="DISCOVERY_PROGRESS"?48:scope==="OPPORTUNITY_SUMMARY"?168:72;}

function fallback(facts:NarrativeFactSet,fp:string):MarketRouteNarrative{
  const known=facts.knownFacts.slice(0,6),uncertainties=facts.uncertainties.slice(0,5);
  return {contractVersion:MARKETROUTE_CONVERSATION_CONTRACT_VERSION,scope:facts.scope,headline:facts.subject,summary:known[0]??facts.status,whyItMatters:known[1]??"MarketRoute is keeping the commercial picture tied to the evidence it currently has.",known,uncertainties,recommendation:facts.deterministicRecommendation,nextAction:facts.deterministicNextAction,evidenceReferences:facts.allowedEvidenceReferences.slice(0,12),sourceFingerprint:fp,generatedAt:new Date().toISOString(),generation:"DETERMINISTIC_FALLBACK"};
}
function validateOutput(value:any,facts:NarrativeFactSet,fp:string):Omit<MarketRouteNarrative,"contractVersion"|"scope"|"sourceFingerprint"|"generatedAt"|"generation">{
  const fields=[value?.headline,value?.summary,value?.whyItMatters,value?.recommendation,value?.nextAction];if(fields.some(v=>typeof v!=="string"||!v.trim()))throw new Error("MARKETROUTE_NARRATOR_OUTPUT_INVALID");
  const joined=[...fields,...cleanList(value.known,6),...cleanList(value.uncertainties,5)].join(" ");if(internalLanguage.test(joined))throw new Error("MARKETROUTE_NARRATOR_INTERNAL_LANGUAGE_REJECTED");
  const allowed=new Set(facts.allowedEvidenceReferences);const refs=cleanList(value.evidenceReferences,12);if(refs.some(ref=>!allowed.has(ref)))throw new Error("MARKETROUTE_NARRATOR_EVIDENCE_REFERENCE_INVALID");
  return {headline:value.headline.trim(),summary:value.summary.trim(),whyItMatters:value.whyItMatters.trim(),known:cleanList(value.known,6),uncertainties:cleanList(value.uncertainties,5),recommendation:value.recommendation.trim(),nextAction:value.nextAction.trim(),evidenceReferences:refs};
}

export class MarketRouteConversationService{
  constructor(private readonly cache:ConversationCacheRepository=conversationCacheRepositoryFromEnvironment()){}
  private async narrate(facts:NarrativeFactSet):Promise<MarketRouteNarrative>{
    const source={subject:facts.subject,status:facts.status,knownFacts:facts.knownFacts,uncertainties:facts.uncertainties,evidenceReferences:facts.allowedEvidenceReferences,recommendation:facts.deterministicRecommendation,nextAction:facts.deterministicNextAction};const fp=fingerprint(source);
    try{const hit=await this.cache.get<MarketRouteNarrative>({scope:facts.scope,scopeKey:facts.scopeKey,fingerprint:fp,contractVersion:MARKETROUTE_CONVERSATION_CONTRACT_VERSION});if(hit?.payload?.sourceFingerprint===fp)return hit.payload;}catch{}
    const fallbackValue=fallback(facts,fp);
    try{
      const ai=new OpenAIResponsesClient();const model=process.env.OPENAI_NARRATOR_MODEL?.trim()||openAIModel();
      const result=await ai.structured<any>({model,name:"marketroute_customer_narrative",schema:outputSchema as any,maxOutputTokens:1100,usageContext:{requestKind:`NARRATE_${facts.scope}`,organisationId:facts.organisationId??null,campaignId:facts.campaignId??null,origin:"CUSTOMER_EXPLANATION"},instructions:`You are the customer-facing voice of MarketRoute. Explain only the structured engine facts supplied by MarketRoute. The facts are authoritative inputs, not suggestions. Never invent a company fact, contact, route, email, phone number, source, score, confidence, commercial decision, recommendation basis, or next step that is not supported by the supplied facts. Never recalculate or override commercial authority. Never expose internal implementation terms such as R4, R5, R6, UDOSIB, epistemic state, fingerprints, reasoning kinds, authority records, model names, tokens, or database concepts. Distinguish what is known from what remains uncertain. Use concise plain commercial English, first person where natural ("I've found…", "I'm still checking…"). Evidence references must be copied only from the allowed list. Web search is forbidden for narration.`,prompt:`Narrate this MarketRoute state for a customer.\n${JSON.stringify(source)}`});
      const safe=validateOutput(result.value,facts,fp);const narrative:MarketRouteNarrative={contractVersion:MARKETROUTE_CONVERSATION_CONTRACT_VERSION,scope:facts.scope,...safe,sourceFingerprint:fp,generatedAt:new Date().toISOString(),generation:"AI"};
      await this.cache.put({scope:facts.scope,scopeKey:facts.scopeKey,fingerprint:fp,contractVersion:MARKETROUTE_CONVERSATION_CONTRACT_VERSION,payload:narrative as unknown as Record<string,unknown>,model:result.model,organisationId:facts.organisationId,campaignId:facts.campaignId,companyId:facts.companyId,ttlHours:ttlHours(facts.scope)}).catch(()=>{});return narrative;
    }catch{await this.cache.put({scope:facts.scope,scopeKey:facts.scopeKey,fingerprint:fp,contractVersion:MARKETROUTE_CONVERSATION_CONTRACT_VERSION,payload:fallbackValue as unknown as Record<string,unknown>,model:"DETERMINISTIC_FALLBACK",organisationId:facts.organisationId,campaignId:facts.campaignId,companyId:facts.companyId,ttlHours:1}).catch(()=>{});return fallbackValue;}
  }

  discovery(raw:AnonymousDiscoveryStatusRecord,pipeline:AnonymousPipelineStage[]){
    const active=pipeline.find(s=>s.status==="ACTIVE"||s.status==="ATTENTION");const complete=pipeline.filter(s=>s.status==="COMPLETE").length;const m=raw.metrics;
    const known=[`${complete} of ${pipeline.length} discovery stages are complete.`,`${m.scopedCompanies} relevant organisation${m.scopedCompanies===1?" has":"s have"} been brought into scope.`,`${m.researchedCompanies} organisation${m.researchedCompanies===1?" has":"s have"} current research evidence.`,`${m.opportunities} commercial opportunit${m.opportunities===1?"y has":"ies have"} emerged.`,`${m.authorisedRoutes} route${m.authorisedRoutes===1?" is":"s are"} currently ready to pursue.`];
    const uncertain=[] as string[];if(m.scopedCompanies===0)uncertain.push("The target organisation set is still being established.");if(m.opportunities===0)uncertain.push("No organisation has yet earned opportunity state from the current evidence.");if(m.authorisedRoutes===0)uncertain.push("No contact route is ready yet; MarketRoute is still validating access paths.");if(["FAILED","NEEDS_INPUT"].includes(raw.activation.status))uncertain.unshift("The current activation run needs attention before all stages can continue.");
    return this.narrate({scope:"DISCOVERY_PROGRESS",scopeKey:raw.runId,subject:active?.status==="ATTENTION"?"I need to resolve part of your discovery.":m.authorisedRoutes>0?`I've found ${m.authorisedRoutes} route${m.authorisedRoutes===1?"":"s"} ready to pursue.`:active?`I'm ${active.label.toLowerCase()}.`:"Your MarketRoute discovery is saved.",status:`Activation ${raw.activation.status}; active stage ${active?.key??"READY"}.`,knownFacts:known,uncertainties:uncertain,allowedEvidenceReferences:[],deterministicRecommendation:m.authorisedRoutes>0?"Review the routes that are ready while MarketRoute finishes the remaining authorised research.":"Let MarketRoute continue until the strongest organisations have enough evidence to evaluate and route.",deterministicNextAction:active?.status==="ATTENTION"?"The run is saved; resolve the activation issue and retry without discarding completed work.":"No action is required while the current discovery work continues."});
  }

  commandCentre(model:CommandCentreReadModel){
    const campaigns=Array.isArray(model.campaigns)?model.campaigns:[];let scoped=0,opps=0,actionable=0,reviewable=0;for(const row of campaigns){const metrics=object(row.metrics);scoped+=number(metrics.scopedCompanies);opps+=number(metrics.materialisedOpportunities);const dispositions=object(metrics.dispositionCounts),workflows=object(metrics.workflowCounts);actionable+=number(dispositions.ACTIONABLE);reviewable+=number(workflows.REVIEWABLE);}
    return this.narrate({scope:"COMMAND_CENTRE",scopeKey:model.organisation.organisationId,organisationId:model.organisation.organisationId,subject:actionable>0?`${actionable} opportunit${actionable===1?"y is":"ies are"} ready to pursue.`:"I'm still building your strongest routes.",status:`${campaigns.length} campaign(s); ${scoped} scoped companies; ${opps} opportunities; ${actionable} actionable; ${reviewable} reviewable.`,knownFacts:[`${scoped} companies are currently in scope.`,`${opps} companies have earned opportunity state.`,`${actionable} opportunities currently have the authority required to pursue them.`,`${reviewable} opportunities currently need a human decision.`],uncertainties:opps===0?["No company has yet earned opportunity state from the current evidence."]:actionable===0?["Opportunities exist, but none currently has the complete commercial, route and contact case required for action."]:[],allowedEvidenceReferences:[],deterministicRecommendation:actionable>0?"Start with the opportunities MarketRoute marks ready to pursue.":reviewable>0?"Review the opportunities waiting for your decision while research continues elsewhere.":"Let the active research continue until stronger opportunities emerge.",deterministicNextAction:actionable>0?"Open a ready opportunity to see why it matters and how MarketRoute can reach it.":"Open the active market to see what MarketRoute is researching next."});
  }

  campaign(model:CampaignReadModel){
    const c=object(model.campaign),m=object(model.metrics),opps=objectArray(model.opportunities);const campaignId=text(c.campaignId,"campaign"),orgId=text(c.organisationId,"");const actionable=opps.filter(o=>text(o.disposition)==="ACTIONABLE"||boolean(o.executableNow)).length;const review=opps.filter(o=>text(o.workflowState)==="REVIEWABLE").length;
    return this.narrate({scope:"CAMPAIGN_OVERVIEW",scopeKey:campaignId,organisationId:orgId||null,campaignId,subject:actionable>0?`${actionable} route${actionable===1?" is":"s are"} ready in this market.`:`I'm still reducing this market to the strongest opportunities.`,status:`Campaign ${text(c.workflowState,"UNKNOWN")}; ${number(m.scopedCompanies)} scoped; ${number(m.materialisedOpportunities)} materialised; ${actionable} actionable.`,knownFacts:[`${number(m.scopedCompanies)} companies are currently being evaluated in this market.`,`${number(m.materialisedOpportunities)} companies have earned opportunity state.`,`${actionable} opportunities are currently ready to pursue.`,`${review} opportunities are waiting for a human decision.`],uncertainties:opps.length===0?["No company has yet earned opportunity state in this market."]:actionable===0?["The current opportunities still need stronger commercial, route or contact evidence before action is allowed."]:[],allowedEvidenceReferences:[],deterministicRecommendation:actionable>0?"Prioritise the ready opportunities before asking MarketRoute to widen the market.":"Keep research focused on the current market until the strongest candidates become actionable.",deterministicNextAction:actionable>0?"Open the strongest ready opportunity to review the route in.":"Review the companies already in scope while MarketRoute continues research."});
  }

  opportunity(model:CompanyIntelligenceReadModel,routes:RouteDisplayReadModel){
    const profile=object(model.profile),authority=object(model.authority),truth=object(model.truth),research=object(model.research),r4=object(authority.r4),r5=object(authority.r5),r6=object(authority.r6);const paths=objectArray(routes.paths);const companyId=text(profile.companyId,routes.companyId),companyName=text(profile.companyName,"This company"),executable=boolean(profile.executableNow);const authorised=number(profile.authorisedRoutes||r6.distinctAuthorisedAccessPointCount),structural=number(profile.structuralRoutes||r5.distinctAccessPointCount);const refs=paths.map(p=>text(p.pathFingerprint)).filter(Boolean).slice(0,12);const gaps=objectArray(research.candidates).slice(0,4).map(g=>human(text(g.reasonCode,"Research is still needed.")));
    const readyPaths=paths.filter(path=>boolean(path.authorised));
    const readyContacts=readyPaths.slice(0,3).map(path=>{const name=text(path.personName);const roles=cleanList(path.roleTitles,3);const terminal=object(path.terminalAccessPoint);const kind=human(text(terminal.accessPointKind,"direct route"));return name?`Ready contact: ${name}${roles.length?` — ${roles.join(" / ")}`:""}; current ${kind.toLowerCase()} route verified.`:`Ready organisational route: current ${kind.toLowerCase()} access is available.`;});
    const known=[`Commercial case: ${human(text(r4.decision,"not established"))}.`,`MarketRoute has ${structural} structural route${structural===1?"":"s"} and ${authorised} contact-qualified route${authorised===1?"":"s"}.`,...readyContacts,`Research quality state: ${human(text(truth.entityState,"not yet established"))}.`].slice(0,6);
    const uncertainties=gaps.length?gaps:executable?[]:["The complete commercial, route and contact case is not yet current enough for action."];
    return this.narrate({scope:"OPPORTUNITY_SUMMARY",scopeKey:`${routes.campaignId}:${companyId}`,organisationId:routes.organisationId,campaignId:routes.campaignId,companyId,subject:executable?`${companyName} is ready to pursue.`:`I'm still qualifying ${companyName}.`,status:`Executable ${executable}; commercial ${text(r4.decision,"UNKNOWN")}; route ${text(r5.decision,"UNKNOWN")}; contact ${text(r6.decision,"UNKNOWN")}.`,knownFacts:known,uncertainties,allowedEvidenceReferences:refs,deterministicRecommendation:executable?"This opportunity has the current commercial case and route authority required for action; review the ready routes before contacting the company.":"Keep this opportunity in research until the missing commercial or contact evidence is resolved.",deterministicNextAction:executable?"Review the authorised routes and their evidence.":"Review the open research questions to see what MarketRoute is still trying to establish."});
  }
}
export function marketRouteConversationServiceFromEnvironment(){return new MarketRouteConversationService();}
