import { randomUUID } from "node:crypto";
import { SellerGenomeService } from "../seller-genome/service";
import { SellerGenomeRepository } from "../../platform/database/seller-genome-repository";
import { openAISellerGenomeExtractorFromEnvironment } from "../../platform/ai/openai-seller-genome-extractor";
import { openAITargetDiscoveryProviderFromEnvironment } from "../../platform/ai/openai-target-discovery";
import { productionActivationRepositoryFromEnvironment } from "../../platform/database/production-activation-repository";
function num(name:string,fallback:number,min:number,max:number){const v=Number(process.env[name]??fallback);return Number.isFinite(v)?Math.max(min,Math.min(max,v)):fallback}
function retryable(code:string){return !/SELLER_OFFERING_UNRESOLVED|HARD_CONSTRAINTS_NOT_CANONICALLY_REPRESENTED|TARGET_DISCOVERY_EMPTY|SETUP_/.test(code)}
export async function runWorkspaceActivationOnce(workerId=`ACTIVATION:${randomUUID()}`){const repo=productionActivationRepositoryFromEnvironment();const job=await repo.claim(workerId,new Date().toISOString());if(!job)return null;try{const material={websiteUrl:job.website_url,objectiveText:job.objective_text,targetMarketText:job.target_market_text,hardConstraintsText:job.hard_constraints_text,noHardConstraints:job.no_hard_constraints};const sellerService=new SellerGenomeService(SellerGenomeRepository.fromEnvironment());const persisted=await sellerService.extractAndPersist({organisationId:job.organisation_id,sellerBusinessId:job.seller_business_id,sellerDisplayName:job.seller_name,materialKind:"COMPOSITE",sourceContent:material,extractor:openAISellerGenomeExtractorFromEnvironment(),createdByUserId:job.created_by_user_id});const campaignId=await repo.createCampaign(job.organisation_id,job.seller_business_id,job.objective_text);await sellerService.selectCampaignObjective({organisationId:job.organisation_id,campaignId,genomeSnapshotId:persisted.genomeSnapshotId,objectiveKey:"primary_objective",requestId:randomUUID()});await repo.setResearchPolicy({organisationId:job.organisation_id,campaignId,dailyBudgetUsd:num("MARKETROUTE_DEFAULT_DAILY_RESEARCH_BUDGET_USD",100,1,10000),maxJobCostUsd:num("MARKETROUTE_DEFAULT_MAX_JOB_COST_USD",0.5,0.05,25),maxConcurrentJobs:Math.floor(num("MARKETROUTE_DEFAULT_RESEARCH_CONCURRENCY",2,1,20)),maxWorkUnitsPerPlan:Math.floor(num("MARKETROUTE_DEFAULT_WORK_UNITS_PER_PLAN",4,1,20)),refreshHorizonHours:Math.floor(num("MARKETROUTE_DEFAULT_REFRESH_HORIZON_HOURS",2,1,168))});const discovery=await openAITargetDiscoveryProviderFromEnvironment().discover({sellerName:job.seller_name,sellerDomain:job.canonical_domain,objectiveText:job.objective_text,targetMarketText:job.target_market_text,canonicalSellerGenome:persisted.genome});if(discovery.companies.length===0)throw new Error("MARKETROUTE_TARGET_DISCOVERY_EMPTY");const companyIds:string[]=[];for(const company of discovery.companies)companyIds.push(await repo.ensureCompany(job.organisation_id,campaignId,company));const result={campaignId,genomeSnapshotId:persisted.genomeSnapshotId,semanticCompleteness:persisted.semanticCompleteness,targetCompanyCount:companyIds.length,targetCompanyIds:companyIds,discovery:discovery.metadata};await repo.complete(job.job_id,workerId,result,new Date().toISOString());return{status:"SUCCEEDED" as const,jobId:job.job_id,...result};}catch(error){const code=error instanceof Error?error.message:"MARKETROUTE_ACTIVATION_FAILED";await repo.fail(job.job_id,workerId,code,retryable(code),new Date().toISOString()).catch(()=>undefined);return{status:"FAILED" as const,jobId:job.job_id,error:code};}}
export async function runWorkspaceActivationCron(max=2){const results=[];for(let i=0;i<Math.max(1,Math.min(max,5));i++){const result=await runWorkspaceActivationOnce();if(!result)break;results.push(result);}return{processed:results.length,results};}
