import { timingSafeEqual, randomUUID } from "node:crypto";
import { openAIResearchProviderFromEnvironment } from "../../platform/ai/openai-research-provider";
import { researchAutomationServiceFromEnvironment } from "../research/automation";
import { engagementServiceFromEnvironment } from "../engagement/service";
import { runWorkspaceActivationCron } from "./bootstrap";
import { genesisDatabaseGrowthServiceFromEnvironment } from "../growth/service";

function intEnv(name:string,fallback:number,min:number,max:number){const n=Number(process.env[name]??fallback);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.floor(n))):fallback;}
function secureEqual(a:string,b:string){const aa=Buffer.from(a),bb=Buffer.from(b);return aa.length===bb.length&&timingSafeEqual(aa,bb);}
function serverKeyPresent(){return Boolean(process.env.SUPABASE_SECRET_KEY?.trim()||process.env.SUPABASE_SERVICE_ROLE_KEY?.trim());}
function publicKeyPresent(){return Boolean(process.env.SUPABASE_PUBLISHABLE_KEY?.trim()||process.env.SUPABASE_ANON_KEY?.trim());}
export function assertCronRequest(request:Request){const secret=process.env.CRON_SECRET?.trim();if(!secret)throw new Error("MARKETROUTE_ENV_REQUIRED:CRON_SECRET");if(secret.length<32)throw new Error("MARKETROUTE_CRON_SECRET_TOO_SHORT");const auth=request.headers.get("authorization")??"";if(!secureEqual(auth,`Bearer ${secret}`))throw new Error("MARKETROUTE_CRON_UNAUTHORISED");}
export async function runGrowthCron(){return genesisDatabaseGrowthServiceFromEnvironment().runCycle();}
export async function runResearchCron(){return researchAutomationServiceFromEnvironment(openAIResearchProviderFromEnvironment()).runCycle({maxPlanningTargets:intEnv("MARKETROUTE_CRON_RESEARCH_PLANNING_TARGETS",50,1,500),maxWorkExecutions:intEnv("MARKETROUTE_CRON_RESEARCH_WORK_EXECUTIONS",8,1,50)});}
export async function runBootstrapCron(){return runWorkspaceActivationCron(intEnv("MARKETROUTE_CRON_BOOTSTRAP_BATCH",2,1,5));}
export async function runDeliveryCron(){if(process.env.MARKETROUTE_DELIVERY_ENABLED?.trim().toLowerCase()!=="true")return{status:"DISABLED" as const,processed:0};const max=intEnv("MARKETROUTE_CRON_DELIVERY_BATCH",10,1,50);const service=engagementServiceFromEnvironment();let processed=0,sent=0,failed=0;for(let i=0;i<max;i++){const result=await service.deliverNext(`VERCEL_CRON:${randomUUID()}`);if(!result)break;processed++;if(result.status==="SENT")sent++;else failed++;}return{status:"OK" as const,processed,sent,failed};}
export function productionEnvironmentStatus(){const missing:string[]=[];for(const k of ["SUPABASE_URL","OPENAI_API_KEY","CRON_SECRET","FOUNDER_DASHBOARD_PASSWORD","FOUNDER_DASHBOARD_SESSION_SECRET"])if(!process.env[k]?.trim())missing.push(k);if(!serverKeyPresent())missing.push("SUPABASE_SECRET_KEY_OR_SUPABASE_SERVICE_ROLE_KEY");if(!publicKeyPresent())missing.push("SUPABASE_PUBLISHABLE_KEY_OR_SUPABASE_ANON_KEY");const secret=process.env.CRON_SECRET?.trim()||"";if(secret&&secret.length<32)missing.push("CRON_SECRET_MIN_32_CHARACTERS");const founderPassword=process.env.FOUNDER_DASHBOARD_PASSWORD?.trim()||"";if(founderPassword&&founderPassword.length<12)missing.push("FOUNDER_DASHBOARD_PASSWORD_MIN_12_CHARACTERS");const founderSessionSecret=process.env.FOUNDER_DASHBOARD_SESSION_SECRET?.trim()||"";if(founderSessionSecret&&founderSessionSecret.length<32)missing.push("FOUNDER_DASHBOARD_SESSION_SECRET_MIN_32_CHARACTERS");const deliveryEnabled=process.env.MARKETROUTE_DELIVERY_ENABLED?.trim().toLowerCase()==="true";if(deliveryEnabled){for(const k of ["RESEND_API_KEY","MARKETROUTE_EMAIL_FROM"])if(!process.env[k]?.trim())missing.push(k);}const supabaseKeyMode=process.env.SUPABASE_SECRET_KEY?.trim()&&process.env.SUPABASE_PUBLISHABLE_KEY?.trim()?"CURRENT":process.env.SUPABASE_SERVICE_ROLE_KEY?.trim()&&process.env.SUPABASE_ANON_KEY?.trim()?"LEGACY":"MIXED";return{ok:missing.length===0,missing:[...new Set(missing)],deliveryEnabled,openAIModel:process.env.OPENAI_MODEL?.trim()||"gpt-5.6-luna",supabaseKeyMode};}
