import { ENGAGEMENT_GENERATION_CONTRACT_VERSION,ENGAGEMENT_REVIEW_CONTRACT_VERSION,type CanonicalEngagementMessage,type EngagementChannel,type EngagementStrategyContext } from "../../core/engagement/index";
import type { EngagementGenerationProviderResult,EngagementLanguageProvider,EngagementReviewProviderResult } from "./engagement-provider";
import { OpenAIResponsesClient } from "./openai-responses";
const generationSchema={type:"object",additionalProperties:false,properties:{subjectText:{type:["string","null"]},bodyText:{type:"string"}},required:["subjectText","bodyText"]} as const;
const reviewSchema={type:"object",additionalProperties:false,properties:{verdict:{type:"string",enum:["PASS","REWRITE","BLOCK"]},reasonCodes:{type:"array",items:{type:"string"}},diagnostics:{type:"object",additionalProperties:false,properties:{unsupportedClaim:{type:"boolean"},excessiveCertainty:{type:"boolean"},unprofessionalTone:{type:"boolean"},privacyRisk:{type:"boolean"}},required:["unsupportedClaim","excessiveCertainty","unprofessionalTone","privacyRisk"]}},required:["verdict","reasonCodes","diagnostics"]} as const;
function contextText(c:EngagementStrategyContext){return JSON.stringify({company:{name:c.companyName,domain:c.canonicalDomain},route:{mode:c.routeMode,personName:c.personName,accessPointKind:c.accessPointKind},seller:{objective:c.sellerObjectiveStatement,offerings:c.sellerOfferings},commercialBoundaryFacts:c.commercialBoundaryFacts});}
export class OpenAIEngagementLanguageProvider implements EngagementLanguageProvider{
 constructor(private readonly ai=new OpenAIResponsesClient()){}
 async generate(context:EngagementStrategyContext,channel:EngagementChannel,options:{signal:AbortSignal;previousMessage?:CanonicalEngagementMessage|null;rewriteReasons?:string[]}):Promise<EngagementGenerationProviderResult>{const result=await this.ai.structured<any>({name:"marketroute_engagement_message",schema:generationSchema as any,instructions:"You write concise, professional B2B outreach for MarketRoute. Use only facts present in the provided context. Never invent results, relationships, urgency, familiarity, customers, pain, or personal details. Do not mention internal R4/R5/R6/Truth machinery. The message should make the commercial reason for contact clear without sounding automated or manipulative. If a named person is absent, address the organisation or relevant team rather than inventing a person.",prompt:`Channel: ${channel}\nContext: ${contextText(context)}\n${options.previousMessage?`Previous message requiring rewrite: ${JSON.stringify(options.previousMessage)}\nRewrite reasons: ${(options.rewriteReasons??[]).join(", ")}`:"Create the first outreach draft."}`,signal:options.signal,maxOutputTokens:1600,usageContext:{requestKind:"ENGAGEMENT_GENERATION",organisationId:context.organisationId,campaignId:context.campaignId}});return{contractVersion:ENGAGEMENT_GENERATION_CONTRACT_VERSION,generatorVersion:`OPENAI-RESPONSES:${result.model}:1.0.0`,message:{subjectText:result.value.subjectText,bodyText:result.value.bodyText}};}
 async review(context:EngagementStrategyContext,channel:EngagementChannel,message:CanonicalEngagementMessage,options:{signal:AbortSignal}):Promise<EngagementReviewProviderResult>{const result=await this.ai.structured<any>({name:"marketroute_engagement_review",schema:reviewSchema as any,instructions:"You are a categorical language-quality reviewer, not a commercial authority engine. Return PASS only when the message is professionally written and every factual/commercial statement is supported by the supplied context. Return REWRITE for fixable tone/clarity/unsupported wording. Return BLOCK for privacy-sensitive, deceptive, manipulative, or materially unsupported content. Never use numeric scores or confidence thresholds.",prompt:`Channel: ${channel}\nContext: ${contextText(context)}\nMessage: ${JSON.stringify(message)}`,signal:options.signal,maxOutputTokens:1000,usageContext:{requestKind:"ENGAGEMENT_REVIEW",organisationId:context.organisationId,campaignId:context.campaignId}});return{contractVersion:ENGAGEMENT_REVIEW_CONTRACT_VERSION,reviewerVersion:`OPENAI-RESPONSES:${result.model}:1.0.0`,review:result.value};}
}
export function openAIEngagementLanguageProviderFromEnvironment(){return new OpenAIEngagementLanguageProvider();}
