import { NextResponse } from "next/server";
import { cookies } from "next/headers";
import { engagementServiceFromEnvironment } from "@/application/engagement/service";
import { applicationReadServiceFromEnvironment } from "@/application/read-model/service";
import { sessionServiceFromEnvironment } from "@/application/session/service";
import { ACCESS_COOKIE,ORG_COOKIE } from "@/app/app/_lib/session";
import { sameOriginOrThrow,safeReturnPath } from "@/app/app/_lib/security";
export const runtime="nodejs";export const maxDuration=180;
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){const form=await request.formData();const returnTo=safeReturnPath(form.get("returnTo"));try{sameOriginOrThrow(request);const {id}=await params;const pathFingerprint=String(form.get("pathFingerprint")??"");if(!pathFingerprint)throw new Error("MARKETROUTE_ENGAGEMENT_PATH_REQUIRED");const jar=await cookies();const access=jar.get(ACCESS_COOKIE)?.value;if(!access)throw new Error("MARKETROUTE_AUTH_REQUIRED");const sessionService=sessionServiceFromEnvironment();const session=await sessionService.authenticate(access);const workspace=sessionService.selectWorkspace(session,jar.get(ORG_COOKIE)?.value);await sessionService.assertOpportunityWriteScope(session,id,workspace.organisationId);const read=await applicationReadServiceFromEnvironment().engagement({opportunityId:id});if(!Boolean((read.actions as Record<string,unknown>).canGenerate))throw new Error("MARKETROUTE_ENGAGEMENT_GENERATION_NOT_ALLOWED");await engagementServiceFromEnvironment().createReviewedDraft({opportunityId:id,pathFingerprint});return NextResponse.redirect(new URL(returnTo,request.url),303);}catch(error){const code=encodeURIComponent(error instanceof Error?error.message:"MARKETROUTE_ENGAGEMENT_GENERATION_FAILED");return NextResponse.redirect(new URL(`${returnTo}${returnTo.includes("?")?"&":"?"}actionError=${code}`,request.url),303);}}
