import { createHash } from "node:crypto";
import { billingRepositoryFromEnvironment,type BillingContextRecord } from "../../platform/database/billing-repository";
import { stripeBillingClientFromEnvironment,stripePlanForPriceId,stripePriceIdForPlan,verifyStripeWebhook,type StripePlanCode,type StripeSubscriptionSnapshot } from "../../platform/billing/stripe";
import { commercialAccessServiceFromEnvironment } from "../commercial/service";

function plan(value:string):StripePlanCode{const clean=value.trim().toUpperCase();if(!["STARTER","GROWTH","SCALE"].includes(clean))throw new Error("MARKETROUTE_BILLING_PLAN_INVALID");return clean as StripePlanCode;}
function appBaseUrl(origin:string):string{const configured=process.env.MARKETROUTE_APP_URL?.trim();const candidate=configured||origin;let url:URL;try{url=new URL(candidate);}catch{throw new Error("MARKETROUTE_BILLING_APP_URL_INVALID");}if(!["https:","http:"].includes(url.protocol))throw new Error("MARKETROUTE_BILLING_APP_URL_INVALID");if(process.env.NODE_ENV==="production"&&url.protocol!=="https:")throw new Error("MARKETROUTE_BILLING_APP_URL_HTTPS_REQUIRED");return url.origin;}
function meta(value:Record<string,unknown>,key:string):string|null{const item=value[key];return typeof item==="string"&&item.trim()?item.trim():null;}

export class BillingService {
  private readonly repository=billingRepositoryFromEnvironment();
  private readonly stripe=stripeBillingClientFromEnvironment();
  private readonly commercial=commercialAccessServiceFromEnvironment();
  async context(organisationId:string):Promise<BillingContextRecord>{return this.repository.context(organisationId);}
  private async validatePrice(planCode:StripePlanCode){const catalog=(await this.commercial.plans()).find(row=>row.planCode===planCode);if(!catalog)throw new Error("MARKETROUTE_BILLING_PLAN_NOT_PUBLIC");const priceId=stripePriceIdForPlan(planCode);const price=await this.stripe.price(priceId);const expected=Math.round(catalog.monthlyPriceGbp*100);if(!price.active||price.currency!=="gbp"||price.unitAmount!==expected||price.recurringInterval!=="month")throw new Error("MARKETROUTE_BILLING_PRICE_CONFIGURATION_MISMATCH");return priceId;}
  async checkout(input:{organisationId:string;userId:string;email:string|null;planCode:string;requestOrigin:string}){
    const planCode=plan(input.planCode);const access=await this.commercial.access(input.organisationId);if(access.mode!=="DISCOVERY_FREE")throw new Error(access.mode==="PAID"?"MARKETROUTE_BILLING_ALREADY_SUBSCRIBED":"MARKETROUTE_BILLING_CHECKOUT_NOT_AVAILABLE");const context=await this.repository.context(input.organisationId);if(context.externalSubscriptionId&&!["CANCELLED","EXPIRED"].includes(String(context.entitlementStatus??"")))throw new Error("MARKETROUTE_BILLING_EXISTING_SUBSCRIPTION_REQUIRES_PORTAL");const priceId=await this.validatePrice(planCode);const attempt=await this.repository.beginCheckout({organisationId:input.organisationId,userId:input.userId,planCode});const base=appBaseUrl(input.requestOrigin);const successUrl=`${base}/app/billing/success?session_id={CHECKOUT_SESSION_ID}`;const cancelUrl=`${base}/api/billing/cancel?attempt=${encodeURIComponent(attempt.attemptId)}`;try{const session=await this.stripe.createCheckout({organisationId:input.organisationId,planCode,priceId,customerId:context.externalCustomerId,customerEmail:input.email,successUrl,cancelUrl,attemptId:attempt.attemptId});await this.repository.attachCheckout({attemptId:attempt.attemptId,sessionId:session.id});return session.url;}catch(error){await this.repository.terminateCheckout({attemptId:attempt.attemptId,organisationId:input.organisationId,userId:input.userId,status:"FAILED",reason:error instanceof Error?error.message:"STRIPE_CHECKOUT_CREATE_FAILED"}).catch(()=>undefined);throw error;}
  }
  async cancelCheckout(input:{organisationId:string;userId:string;attemptId:string}){if(!/^[0-9a-f-]{36}$/i.test(input.attemptId))throw new Error("MARKETROUTE_BILLING_CHECKOUT_ATTEMPT_INVALID");await this.repository.terminateCheckout({attemptId:input.attemptId,organisationId:input.organisationId,userId:input.userId,status:"EXPIRED",reason:"CUSTOMER_CANCELLED"});}
  async portal(input:{organisationId:string;requestOrigin:string}){const context=await this.repository.context(input.organisationId);if(!context.externalCustomerId)throw new Error("MARKETROUTE_BILLING_CUSTOMER_NOT_FOUND");return this.stripe.createPortal(context.externalCustomerId,`${appBaseUrl(input.requestOrigin)}/app/plans`);}
  private async reconcileSubscription(subscription:StripeSubscriptionSnapshot,input:{organisationId:string;expectedPlanCode?:StripePlanCode|null;eventId?:string|null;eventType?:string|null;checkoutSessionId?:string|null}){
    const orgFromMeta=meta(subscription.metadata,"marketroute_organisation_id");if(orgFromMeta&&orgFromMeta!==input.organisationId)throw new Error("MARKETROUTE_BILLING_SUBSCRIPTION_ORGANISATION_MISMATCH");const mapped=subscription.priceIds.map(stripePlanForPriceId).filter((value):value is StripePlanCode=>Boolean(value));if(mapped.length!==1||subscription.priceIds.length!==1)throw new Error("MARKETROUTE_BILLING_SUBSCRIPTION_PRICE_UNMAPPED");const planCode=mapped[0]!;if(input.expectedPlanCode&&planCode!==input.expectedPlanCode)throw new Error("MARKETROUTE_BILLING_SUBSCRIPTION_PLAN_MISMATCH");if(!subscription.customerId)throw new Error("MARKETROUTE_BILLING_SUBSCRIPTION_CUSTOMER_MISSING");await this.repository.reconcile({organisationId:input.organisationId,planCode,customerId:subscription.customerId,subscriptionId:subscription.id,providerStatus:subscription.status,periodStart:subscription.currentPeriodStart,periodEnd:subscription.currentPeriodEnd,cancelAtPeriodEnd:subscription.cancelAtPeriodEnd,eventId:input.eventId??null,eventType:input.eventType??null,checkoutSessionId:input.checkoutSessionId??null});return planCode;
  }
  async reconcileCheckout(sessionId:string,organisationId:string){const session=await this.stripe.checkout(sessionId);if(session.status!=="complete")throw new Error("MARKETROUTE_BILLING_CHECKOUT_NOT_COMPLETE");if(session.clientReferenceId!==organisationId)throw new Error("MARKETROUTE_BILLING_CHECKOUT_ORGANISATION_MISMATCH");const metaOrg=meta(session.metadata,"marketroute_organisation_id");if(metaOrg!==organisationId)throw new Error("MARKETROUTE_BILLING_CHECKOUT_METADATA_MISMATCH");const expectedPlan=plan(meta(session.metadata,"marketroute_plan_code")??"");if(!session.subscriptionId)throw new Error("MARKETROUTE_BILLING_CHECKOUT_SUBSCRIPTION_PENDING");const subscription=await this.stripe.subscription(session.subscriptionId);if(session.customerId&&subscription.customerId!==session.customerId)throw new Error("MARKETROUTE_BILLING_CHECKOUT_CUSTOMER_MISMATCH");await this.reconcileSubscription(subscription,{organisationId,expectedPlanCode:expectedPlan,checkoutSessionId:session.id,eventType:"checkout.success_reconcile"});return this.commercial.access(organisationId);}
  async webhook(rawBody:string,signature:string){const event=verifyStripeWebhook(rawBody,signature);const hash=createHash("sha256").update(rawBody,"utf8").digest("hex");const fresh=await this.repository.beginEvent({eventId:event.id,eventType:event.type,payloadSha256:hash});if(!fresh)return {duplicate:true,eventId:event.id};try{
      if(event.type==="checkout.session.completed"){const sessionId=typeof event.dataObject.id==="string"?event.dataObject.id:"";const session=await this.stripe.checkout(sessionId);const organisationId=session.clientReferenceId??meta(session.metadata,"marketroute_organisation_id");if(!organisationId||!session.subscriptionId)throw new Error("MARKETROUTE_BILLING_CHECKOUT_EVENT_SCOPE_MISSING");const expectedPlan=plan(meta(session.metadata,"marketroute_plan_code")??"");if(session.status!=="complete")throw new Error("MARKETROUTE_BILLING_CHECKOUT_NOT_COMPLETE");const subscription=await this.stripe.subscription(session.subscriptionId);if(session.customerId&&subscription.customerId!==session.customerId)throw new Error("MARKETROUTE_BILLING_CHECKOUT_CUSTOMER_MISMATCH");await this.reconcileSubscription(subscription,{organisationId,expectedPlanCode:expectedPlan,eventId:event.id,eventType:event.type,checkoutSessionId:session.id});await this.repository.finishEvent({eventId:event.id,status:"PROCESSED",metadata:{organisationId,subscriptionId:subscription.id}});return {duplicate:false,eventId:event.id};}
      if(["customer.subscription.created","customer.subscription.updated","customer.subscription.deleted"].includes(event.type)){const subscriptionId=typeof event.dataObject.id==="string"?event.dataObject.id:"";const eventMeta=event.dataObject.metadata&&typeof event.dataObject.metadata==="object"&&!Array.isArray(event.dataObject.metadata)?event.dataObject.metadata as Record<string,unknown>:{};const organisationId=meta(eventMeta,"marketroute_organisation_id");if(!organisationId)throw new Error("MARKETROUTE_BILLING_SUBSCRIPTION_EVENT_ORGANISATION_MISSING");const subscription=await this.stripe.subscription(subscriptionId);await this.reconcileSubscription(subscription,{organisationId,eventId:event.id,eventType:event.type});await this.repository.finishEvent({eventId:event.id,status:"PROCESSED",metadata:{organisationId,subscriptionId}});return {duplicate:false,eventId:event.id};}
      await this.repository.finishEvent({eventId:event.id,status:"IGNORED"});return {duplicate:false,eventId:event.id};
    }catch(error){await this.repository.finishEvent({eventId:event.id,status:"FAILED",errorCode:error instanceof Error?error.message:"MARKETROUTE_BILLING_WEBHOOK_FAILED"}).catch(()=>undefined);throw error;}}
}
export function billingServiceFromEnvironment(){return new BillingService();}
