import { commandCentre,resolveCampaignId } from "@/app/app/_lib/data";
import { workspaceSessionOrRedirect } from "@/app/app/_lib/session";
import { applicationReadServiceFromEnvironment } from "@/application/read-model/service";
import { commercialAccessServiceFromEnvironment } from "@/application/commercial/service";
import { asObject,asObjectArray,campaignListItem,formatDateTime,statusTone,text } from "@/application/read-model/presentation";
import { CampaignSwitcher,EmptyState,humanStatus,Icon,IntelligenceTable,MetricCard,PageHeader,Panel,SectionHeading,StatusBadge } from "@/ui";

function capacity(value:{limitUnits:number|null;usedUnits:number;reservedUnits:number;remainingUnits:number|null}){if(value.limitUnits===null)return{label:"Included",meta:"No metered research limit on this workspace"};if(value.limitUnits<=0)return{label:"Discovery",meta:"One-time discovery allowance"};const pct=Math.round((Math.max(0,value.remainingUnits??0)/value.limitUnits)*100);return{label:`${pct}%`,meta:`${value.usedUnits} used · ${value.reservedUnits} in progress`};}
export default async function Research({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
  const query=await searchParams;const {workspace}=await workspaceSessionOrRedirect();const cc=await commandCentre(workspace.organisationId);const campaigns=asObjectArray(cc.campaigns).map(campaignListItem);const campaignId=resolveCampaignId(cc,typeof query.campaign==="string"?query.campaign:null);
  if(!campaignId)return <div><PageHeader eyebrow="RESEARCH" title="Research the gaps" accent="that change a decision." description="MarketRoute investigates the questions that affect commercial relevance, route quality and buyer access."/><Panel><EmptyState icon="research" title="No active market" body="Research appears after MarketRoute has a market brief to work from."/></Panel></div>;
  const [model,access]=await Promise.all([applicationReadServiceFromEnvironment().researchActivity({organisationId:workspace.organisationId,campaignId}),commercialAccessServiceFromEnvironment().access(workspace.organisationId)]);const budget=asObject(model.budget),work=asObjectArray(model.workUnits),runs=asObjectArray(model.schedulerRuns),cap=capacity(access.researchCapacity);const active=Number(budget.activeJobs??0);const completed=work.filter(w=>text(asObject(w.job).status)==="SUCCEEDED").length;const blockers=work.filter(w=>text(w.tier)==="DECISION_BLOCKER").length;
  return <div>
    <PageHeader eyebrow="RESEARCH" title="MarketRoute is checking" accent="what changes the decision." description="Genesis works from explicit knowledge gaps. You see what is being checked and why; the underlying model spend stays an internal MarketRoute concern." actions={<CampaignSwitcher campaigns={campaigns.map(c=>({campaignId:c.campaignId,name:c.name,workflowState:c.workflowState}))} current={campaignId} action="/app/research"/>}/>
    <section className="mr-metric-grid"><MetricCard label="Research capacity" value={cap.label} meta={cap.meta} icon={<Icon name="research"/>} accent/><MetricCard label="Checks in progress" value={String(active)} meta="Current autonomous work" icon={<Icon name="clock"/>}/><MetricCard label="Recent checks completed" value={String(completed)} meta="Completed work in this view" icon={<Icon name="check"/>}/><MetricCard label="Decision blockers" value={String(blockers)} meta="Questions that can change readiness" icon={<Icon name="warning"/>}/></section>
    <Panel><SectionHeading eyebrow="WHAT I'M CHECKING" title="Current research work" description="Decision blockers come first, then freshness repair and useful enrichment. MarketRoute does not research indiscriminately."/>{work.length===0?<EmptyState icon="research" title="Research queue is clear" body="There are no recent research checks for this market."/>:<IntelligenceTable head={["Focus","Priority","What MarketRoute is checking","Why now","Status","Updated"]}>{work.map(w=>{const job=asObject(w.job),status=text(job.status,"WAITING");return <tr key={text(w.workUnitId)}><td><span className="mr-table-state">{humanStatus(text(w.layer))}</span></td><td>{text(w.tier)==="DECISION_BLOCKER"?<StatusBadge compact label="Decision blocker" tone="amber"/>:humanStatus(text(w.tier))}</td><td><strong className="mr-table-primary">{humanStatus(text(w.action))}</strong></td><td>{humanStatus(text(w.reasonCode))}</td><td><StatusBadge compact label={humanStatus(status)} title={status} tone={statusTone(status)}/></td><td>{formatDateTime(job.updatedAt??w.updatedAt)}</td></tr>})}</IntelligenceTable>}</Panel>
    <Panel emphasis="quiet"><SectionHeading eyebrow="RECENT ACTIVITY" title="Research is persistent and recoverable" description="Completed work stays attached to the market. If a cycle retries, MarketRoute resumes from persisted state rather than starting the market over."/>{runs.length===0?<EmptyState icon="clock" title="No research activity recorded" body="The first research cycle will appear here once Genesis begins work."/>:<div className="mr-run-list">{runs.slice(0,12).map(r=>{const status=text(r.status);return <div key={text(r.runId)}><StatusBadge compact label={humanStatus(status)} title={status} tone={statusTone(status)}/><span>{formatDateTime(r.startedAt)}</span><strong>{status==="SUCCEEDED"?"Research cycle complete":"Research cycle"}</strong></div>})}</div>}</Panel>
  </div>;
}
